name: TMNet_single_frame
use_tb_logger: false
model: VideoSR_base
distortion: sr
scale: 4
gpu_ids: [0, 1, 2, 3]
dist: true
time_pth: ~

datasets:
  train:
    name: Vimeo7
    mode: Vimeo7
    interval_list: [1]
    random_reverse: true
    border_mode: false
    dataroot_GT: ./datasets/vimeo-90k_septuplet/vimeo7_train_GT.lmdb
    dataroot_LQ: ./datasets/vimeo-90k_septuplet/vimeo7_train_LR7.lmdb
    cache_keys: ./datasets/vimeo-90k_septuplet/Vimeo7_train_keys.pkl

    N_frames: 7
    use_shuffle: true
    n_workers: 6 # per GPU
    batch_size: 24 # total
    GT_size: 128 
    LQ_size: 32
    LR_resolution: [3, 64, 112]
    HR_resolution: [3, 256, 448]
    use_flip: true
    use_rot: true
    color: RGB
    use_time: false

network_G:
  which_model_G: TMNet
  nf: 64
  nframes: 7
  groups: 8
  front_RBs: 5
  mid_RBs: 0
  back_RBs: 40
  HR_in: false

path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

train:
  lr_G: !!float 4e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  warmup_iter: -1
  T_period: [150000, 150000, 150000, 150000]
  restarts: [150000, 300000, 450000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 5e3

  manual_seed: 0

logger:
  print_freq: 1
  save_checkpoint_freq: !!float 5e3